# Generated by Django 4.2.5 on 2023-12-03 04:04

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location_pin_code_location_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='pin_code',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photos',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=users.utils.user_directory_path),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_1',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=localflavor.us.models.USStateField(default='NY', max_length=2),
        ),
    ]
