# Generated by Django 4.2.5 on 2024-01-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_card_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card_details',
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
