# Generated by Django 4.2.5 on 2023-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listings_brand_listings_color_listings_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='color',
            field=models.CharField(max_length=24),
        ),
    ]
