# Generated by Django 4.2.5 on 2023-12-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_photo'),
        ('main', '0003_alter_listings_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
