# Generated by Django 4.2.5 on 2023-12-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_likedlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_value',
            field=models.IntegerField(default=100),
        ),
    ]
