# Generated by Django 4.2.5 on 2024-01-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='profile',
        ),
    ]
